# Prometheus 配置文件
# 用于监控 WebRTC 信令服务器

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'bdwind-gstreamer-monitor'

# 告警规则文件
rule_files:
  - "alert_rules.yml"

# 告警管理器配置
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# 抓取配置
scrape_configs:
  # Prometheus 自身监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: /metrics

  # WebRTC 信令服务器监控
  - job_name: 'signaling-server'
    static_configs:
      - targets: ['signaling-server:8080']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s
    
    # 自定义标签
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'signaling-server'
      - source_labels: [__address__]
        target_label: service
        replacement: 'bdwind-gstreamer'

  # 健康检查监控
  - job_name: 'signaling-health'
    static_configs:
      - targets: ['signaling-server:8080']
    scrape_interval: 30s
    metrics_path: /health
    scrape_timeout: 5s

  # Redis 监控
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s
    metrics_path: /metrics

  # Node Exporter (系统监控)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # cAdvisor (容器监控)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s
    metrics_path: /metrics

  # 黑盒监控 (外部服务检查)
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://signaling-server:8080/health
        - http://signaling-server:8080/api/signaling/status
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

# 远程写入配置 (可选)
remote_write:
  - url: "http://remote-storage:9201/write"
    queue_config:
      max_samples_per_send: 1000
      max_shards: 200
      capacity: 2500

# 远程读取配置 (可选)
remote_read:
  - url: "http://remote-storage:9201/read"