# WebRTC 信令服务器配置文件
# 支持 request-offer 和 ping 消息处理的完整配置

# 服务器基础配置
server:
  # 服务器监听地址和端口
  host: "0.0.0.0"
  port: 8080
  
  # 服务器标识和版本
  name: "bdwind-gstreamer-signaling"
  version: "1.0.0"
  
  # 运行模式: development, production
  mode: "production"

# Web 服务器配置
webserver:
  # HTTP 服务器配置
  host: "0.0.0.0"
  port: 8080
  
  # 静态文件服务
  static_files: "./internal/webserver/static"
  static_route: "/static"
  
  # CORS 配置
  cors:
    enabled: true
    allowed_origins: ["*"]
    allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allowed_headers: ["*"]
    
  # TLS/SSL 配置 (可选)
  tls:
    enabled: false
    cert_file: "/path/to/cert.pem"
    key_file: "/path/to/key.pem"
    
  # 请求限制
  limits:
    max_request_size: "10MB"
    read_timeout: "30s"
    write_timeout: "30s"
    idle_timeout: "120s"

# WebRTC 信令配置
webrtc:
  # 信令服务器配置
  signaling:
    # 启用信令服务
    enabled: true
    
    # 连接管理
    max_connections: 1000
    connection_timeout: "60s"
    heartbeat_interval: "30s"
    cleanup_interval: "5m"
    
    # 消息配置
    max_message_size: 65536
    max_data_size: 32768
    message_buffer_size: 256
    
    # 协议支持
    supported_protocols: ["gstreamer-1.0", "selkies"]
    default_protocol: "gstreamer-1.0"
    auto_detect_protocol: true
    
    # 错误处理
    error_recovery: true
    max_retry_attempts: 3
    retry_delay: "3s"
    
  # ICE 服务器配置
  ice_servers:
    # Google STUN 服务器
    - urls: ["stun:stun.l.google.com:19302"]
    - urls: ["stun:stun1.l.google.com:19302"]
    - urls: ["stun:stun2.l.google.com:19302"]
    
    # 自定义 TURN 服务器 (可选)
    # - urls: ["turn:your-turn-server.com:3478"]
    #   username: "your-username"
    #   credential: "your-password"
    #   credential_type: "password"
    
  # WebRTC 连接配置
  peer_connection:
    # ICE 配置
    ice_connection_timeout: "30s"
    ice_gathering_timeout: "10s"
    ice_candidate_pool_size: 10
    
    # 媒体配置
    bundle_policy: "max-bundle"
    rtcp_mux_policy: "require"
    
    # 数据通道配置
    data_channel:
      enabled: true
      ordered: true
      max_retransmits: 3
      
  # 编解码器配置
  codecs:
    video:
      preferred: ["H264", "VP8", "VP9"]
      h264:
        profile: "baseline"
        level: "3.1"
        packetization_mode: 1
      vp8:
        max_fr: 30
        max_fs: 3600
      vp9:
        profile_id: 0
        
    audio:
      preferred: ["OPUS", "PCMU", "PCMA"]
      opus:
        max_playback_rate: 48000
        stereo: true
        use_inband_fec: true
        
  # 统计信息配置
  stats:
    enabled: true
    collection_interval: "5s"
    retention_period: "1h"
    include_system_stats: true

# GStreamer 配置
gstreamer:
  # 管道配置
  pipeline:
    # 视频源配置
    video_source: "videotestsrc"
    video_source_params:
      pattern: "smpte"
      is_live: true
      
    # 音频源配置  
    audio_source: "audiotestsrc"
    audio_source_params:
      wave: "sine"
      freq: 440
      is_live: true
      
    # 视频编码器
    video_encoder: "x264enc"
    video_encoder_params:
      tune: "zerolatency"
      speed_preset: "ultrafast"
      bitrate: 2000
      
    # 音频编码器
    audio_encoder: "opusenc"
    audio_encoder_params:
      bitrate: 128000
      
  # 缓冲区配置
  buffers:
    video_buffer_size: 1024
    audio_buffer_size: 512
    max_lateness: "20ms"
    
  # 性能配置
  performance:
    threads: 4
    latency_mode: "low"
    drop_on_latency: true

# 日志配置
logging:
  # 日志级别: debug, info, warn, error
  level: "info"
  
  # 日志格式: text, json
  format: "json"
  
  # 日志输出
  output: "/var/log/bdwind-gstreamer.log"
  
  # 日志轮转
  rotation:
    enabled: true
    max_size: "100MB"
    max_age: "7d"
    max_backups: 10
    compress: true
    
  # 结构化日志字段
  fields:
    service: "bdwind-gstreamer"
    version: "1.0.0"
    
  # 特定组件日志级别
  components:
    signaling: "debug"
    webrtc: "info"
    gstreamer: "warn"

# 监控配置
monitoring:
  # 健康检查
  health_check:
    enabled: true
    endpoint: "/health"
    interval: "30s"
    
  # 指标收集
  metrics:
    enabled: true
    endpoint: "/metrics"
    format: "prometheus"
    
    # 自定义指标
    custom_metrics:
      - name: "signaling_connections_total"
        type: "counter"
        help: "Total number of signaling connections"
        
      - name: "message_processing_duration_seconds"
        type: "histogram"
        help: "Message processing duration in seconds"
        buckets: [0.001, 0.01, 0.1, 1.0, 10.0]
        
  # 性能分析
  profiling:
    enabled: false
    endpoint: "/debug/pprof"
    
  # 分布式追踪
  tracing:
    enabled: false
    jaeger_endpoint: "http://localhost:14268/api/traces"

# 安全配置
security:
  # 认证配置
  authentication:
    enabled: false
    type: "jwt"  # jwt, basic, oauth2
    
    # JWT 配置
    jwt:
      secret: "your-jwt-secret"
      expiration: "24h"
      issuer: "bdwind-gstreamer"
      
  # 授权配置
  authorization:
    enabled: false
    default_role: "user"
    
  # 速率限制
  rate_limiting:
    enabled: true
    requests_per_minute: 60
    burst_size: 10
    
  # IP 白名单/黑名单
  ip_filtering:
    enabled: false
    whitelist: []
    blacklist: []

# 数据库配置 (可选)
database:
  enabled: false
  type: "sqlite"  # sqlite, postgres, mysql
  
  # SQLite 配置
  sqlite:
    path: "/var/lib/bdwind-gstreamer/data.db"
    
  # PostgreSQL 配置
  postgres:
    host: "localhost"
    port: 5432
    database: "bdwind_gstreamer"
    username: "bdwind"
    password: "password"
    ssl_mode: "disable"
    
  # 连接池配置
  pool:
    max_open_connections: 25
    max_idle_connections: 5
    connection_max_lifetime: "1h"

# 缓存配置
cache:
  enabled: true
  type: "memory"  # memory, redis
  
  # 内存缓存配置
  memory:
    max_size: "100MB"
    ttl: "1h"
    cleanup_interval: "10m"
    
  # Redis 配置
  redis:
    host: "localhost"
    port: 6379
    password: ""
    database: 0
    pool_size: 10

# 消息队列配置 (可选)
message_queue:
  enabled: false
  type: "memory"  # memory, redis, rabbitmq
  
  # 内存队列配置
  memory:
    buffer_size: 1000
    
  # Redis 队列配置
  redis:
    host: "localhost"
    port: 6379
    password: ""
    database: 1
    
  # RabbitMQ 配置
  rabbitmq:
    url: "amqp://guest:guest@localhost:5672/"
    exchange: "bdwind-gstreamer"
    queue: "signaling-messages"

# 开发配置
development:
  # 调试模式
  debug: false
  
  # 热重载
  hot_reload: false
  
  # 测试模式
  test_mode: false
  
  # 模拟数据
  mock_data: false
  
  # 开发工具
  dev_tools:
    enabled: false
    pprof: true
    expvar: true

# 生产配置
production:
  # 优化设置
  optimize: true
  
  # 资源限制
  limits:
    max_memory: "2GB"
    max_cpu: "2.0"
    max_file_descriptors: 65536
    
  # 故障恢复
  recovery:
    auto_restart: true
    max_restart_attempts: 5
    restart_delay: "10s"
    
  # 备份配置
  backup:
    enabled: false
    interval: "24h"
    retention: "7d"
    location: "/var/backups/bdwind-gstreamer"

# 集群配置 (可选)
cluster:
  enabled: false
  
  # 节点配置
  node:
    id: "node-1"
    role: "primary"  # primary, secondary
    
  # 服务发现
  discovery:
    type: "static"  # static, consul, etcd
    nodes: ["localhost:8080"]
    
  # 负载均衡
  load_balancing:
    strategy: "round_robin"  # round_robin, least_connections, ip_hash
    health_check_interval: "30s"

# 插件配置 (可选)
plugins:
  enabled: false
  directory: "./plugins"
  
  # 启用的插件
  enabled_plugins:
    - "auth-plugin"
    - "metrics-plugin"
    
  # 插件配置
  config:
    auth-plugin:
      provider: "ldap"
      server: "ldap://localhost:389"
      
    metrics-plugin:
      export_interval: "60s"
      export_format: "json"