# Wayland Desktop Capture Configuration Example
# This file demonstrates the configuration options for Wayland desktop capture

# Display settings
display_id: "wayland-0"   # Wayland display ID
frame_rate: 30            # Capture frame rate (1-120 fps)
width: 1920               # Capture width (1-7680 pixels)
height: 1080              # Capture height (1-4320 pixels)

# Display server settings
use_wayland: true         # Use Wayland instead of X11
auto_detect: true         # Auto-detect display server

# Capture options
show_pointer: false       # Show mouse pointer in capture
use_damage: false         # Use damage events (not applicable for Wayland)
buffer_size: 10           # Buffer size (1-100)
quality: "medium"         # Quality preset: low, medium, high

# Optional capture region (comment out to capture full screen)
# Note: Wayland uses crop- properties instead of start/end coordinates
capture_region:
  x: 100                  # X offset (crop-x)
  y: 100                  # Y offset (crop-y)
  width: 800              # Region width (crop-width)
  height: 600             # Region height (crop-height)

# Multi-monitor support examples:
# For output 0: "wayland-0"
# For output 1: "wayland-1"
# For output 2: "wayland-2"
# Note: Actual output names depend on the Wayland compositor