# X11 Desktop Capture Configuration Example
# This configuration demonstrates various X11 desktop capture scenarios

# Basic X11 desktop capture configuration
display_id: ":0"           # X11 display identifier
frame_rate: 30             # Capture frame rate (fps)
width: 1920                # Capture width (pixels)
height: 1080               # Capture height (pixels)
use_wayland: false         # Use X11 (not Wayland)
auto_detect: false         # Don't auto-detect display server
show_pointer: true         # Show mouse pointer in capture
use_damage: true           # Use damage events for optimization
buffer_size: 10            # Buffer size for capture
quality: "high"            # Quality preset (low, medium, high)

# Optional: Capture a specific region instead of full screen
# capture_region:
#   x: 100                 # Start X coordinate
#   y: 100                 # Start Y coordinate  
#   width: 800             # Region width
#   height: 600            # Region height

# Multi-monitor examples:
# For primary monitor: ":0" or ":0.0"
# For second monitor: ":0.1"
# For third monitor: ":0.2"

# Performance optimization settings for X11:
# - use_damage: true enables damage event optimization
# - quality: "low" uses RGB format for better performance
# - quality: "medium" uses BGRx format (default)
# - quality: "high" uses BGRA format for best quality

# Region capture examples:
# Full HD region: width: 1920, height: 1080
# HD region: width: 1280, height: 720
# Custom window region: x: 100, y: 100, width: 800, height: 600